version: 2
models:
  - sqlPath: src/models/staging/my_second_dbt_model.sql
    name: my_second_dbt_model
    $depends_on: []
    $lastModified: 1682077921265
    description: docs.dbt_project.my_second_dbt_model_3ba0a9e2-1044-478a-8750-925020b17cc7
    config:
      tags:
        - test
    columns:
      - name: id
        description: The primary key for this table
        tests:
          - unique
          - not_null
    meta:
      asset_status: deprecated
      experts:
        users:
          - pawel.paulinski@y42.com
          - simon.jornet@y42.com
        teams: []
    tests: []
sources: []
metrics:
  - name: rolling_new_customers
    label: New Customers
    model: ref('my_first_dbt_model')
    description: The 14 day rolling count of paying customers using the product
    calculation_method: count_distinct
    expression: user_id
    timestamp: signup_date
    time_grains:
      - day
      - week
      - month
      - quarter
      - year
    dimensions:
      - plan
      - country
    window:
      count: 14
      period: day
    filters:
      - field: is_paying
        operator: is
        value: "true"
      - field: lifetime_value
        operator: ">="
        value: "100"
      - field: company_name
        operator: "!="
        value: "'Acme, Inc'"
      - field: signup_date
        operator: ">="
        value: "'2020-01-01'"
    config:
      enabled: true
      treat_null_values_as_zero: true
    meta:
      team: Finance
