version: 2
models:
  - name: my_second_dbt_model
    description: blabla
    config:
      tags:
        - test
    columns:
      - name: id
    meta:
      asset_status: deprecated
      experts:
        users:
          - pawel.paulinski@y42.com
          - simon.jornet@y42.com
        teams: []
    tests: []
  - name: my_second_dbt_model
    description: docs.dbt_project.my_second_dbt_model_2ce47a11-6c09-4aaa-a5d4-13f6f5513225
    config:
      tags:
        - test
    columns:
      - name: id
        description: The primary key for this table
        tests:
          - unique
          - not_null
    meta:
      asset_status: deprecated
      experts:
        users:
          - pawel.paulinski@y42.com
        teams: []
    tests: []
sources: []
metrics:
  - name: rolling_new_customers
    label: New Customers
    model: ref('my_first_dbt_model')
    description: The 14 day rolling count of paying customers using the product
    calculation_method: count_distinct
    expression: user_id
    timestamp: signup_date
    time_grains:
      - day
      - week
      - month
      - quarter
      - year
    dimensions:
      - plan
      - country
    window:
      count: 14
      period: day
    filters:
      - field: is_paying
        operator: is
        value: "true"
      - field: lifetime_value
        operator: ">="
        value: "100"
      - field: company_name
        operator: "!="
        value: "'Acme, Inc'"
      - field: signup_date
        operator: ">="
        value: "'2020-01-01'"
    config:
      enabled: true
      treat_null_values_as_zero: true
    meta:
      team: Finance
exposures:
  - name: weekly_jaffle_metrics
    label: Jaffles by the Week
    type: dashboard
    maturity: high
    url: https://bi.tool/dashboards/1
    description: >
      Did someone say "exponential growth"?

    depends_on:
      - ref('my_first_dbt_model')

    owner:
      name: Callum McData
      email: data@jaffleshop.com
