version: 2
sources:
  - name: intercom
    meta:
      config:
        type: intercom
        connection: test_connection_3_2
        settings:
          start_date: 2021-12-31T23:00:00Z
      asset_status: verified
    tables: []
  - name: airbyte_bigquery
    meta:
      config:
        type: source-bigquery
        connection: btt_bigquery
      asset_status: verified
    tables:
      - name: repeated_record
        meta:
          source_config:
            import: repeated_record
            columns:
              - repeated_record
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                repeated_record:
                  type: object
            group: playground
            _datos_write_settings:
              max_flatten_depth: 0
              decimals: false
            supported_sync_modes:
              - full_refresh
              - incremental
        columns:
          - name: repeated_record
      - name: from_eu_playground
        meta:
          source_config:
            import: from_eu_playground
            columns:
              - id
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                id:
                  type: string
    description: ""
