models:
  - name: my_second_dbt_model
    description: A starter dbt model
    config:
      tags:
        - test
    columns:
      - name: id
        description: The primary key for this table
        tests:
          - unique
          - not_null
    meta:
      asset_status: deprecated
      experts:
        users:
          - pawel.paulinski@y42.com
        teams: []
