version: 2
models:
  - name: my_first_dbt_model
    config:
      tags:
        - hai_test
    description: this is my first dbt model
    meta:
      experts:
        users:
          - aliaksei.bahamazau@y42.com
          - johannes.pittgens@y42.com
        teams: []
    columns:
      - name: ID
        description: ""
        data_type: FLOAT
        tests:
          - unique
  - name: my_second_dbt_model
    columns:
      - name: ID
        data_type: FLOAT
    config:
      tags:
        - hai_test
        - static
        - sadfsd
sources: []
