
  WITH FAKE_DATA AS (
    SELECT
      null AS HAI_NUMBER_COLUMN_STUFF,
      null AS HAI_DECIMAL_COLUMN_STUFF,
      null AS HAI_NUMERIC_COLUMN_STUFF,
      null AS HAI_INT_COLUMN_STUFF,
      null AS HAI_INTEGER_COLUMN_STUFF,
      null AS HAI_BIGINT_COLUMN_STUFF,
      null AS HAI_SMALLINT_COLUMN_STUFF,
      null AS HAI_TINYINT_COLUMN_STUFF,
      null AS HAI_BYTEINT_COLUMN_STUFF,
      null AS HAI_FLOAT_COLUMN_STUFF,
      null AS HAI_FLOAT4_COLUMN_STUFF,
      null AS HAI_FLOAT8_COLUMN_STUFF,
      null AS HAI_DOUBLE_COLUMN_STUFF,
      null AS HAI_DOUBLE_PRECISION_COLUMN_STUFF,
      null AS HAI_REAL_COLUMN_STUFF,
      null AS HAI_VARCHAR_COLUMN_STUFF,
      null AS HAI_CHAR_COLUMN_STUFF,
      null AS HAI_CHARACTER_COLUMN_STUFF,
      null AS HAI_STRING_COLUMN_STUFF,
      null AS HAI_TEXT_COLUMN_STUFF,
      null AS HAI_BINARY_COLUMN_STUFF,
      null AS HAI_VARBINARY_COLUMN_STUFF,
      null AS HAI_BOOLEAN_COLUMN_STUFF,
      null AS HAI_DATE_COLUMN_STUFF,

      null AS HAI_DATETIME_COLUMN_STUFF,

      null AS HAI_TIME_COLUMN_STUFF,

      null AS HAI_TIMESTAMP_COLUMN_STUFF,

      null AS HAI_TIMESTAMP_LTZ_COLUMN_STUFF,

      null AS HAI_TIMESTAMP_NTZ_COLUMN_STUFF,

      null AS HAI_TIMESTAMP_TZ_COLUMN_STUFF,

      null AS HAI_VARIANT_COLUMN_STUFF,

      Null AS HAI_OBJECT_COLUMN_STUFF,
      ARRAY[] AS HAI_ARRAY_COLUMN_STUFF,
      Null AS HAI_GEOGRAPHY_COLUMN_STUFF
  )
  SELECT *
  FROM FAKE_DATA
