WITH FAKE_DATA AS (
    SELECT
        null AS HAI_NUMBER_COLUMN_STUFF,
        null AS HAI_DECIMAL_COLUMN_STUFF,
        null AS HAI_NUMERIC_COLUMN_STUFF,
        null AS HAI_STRING_COLUMN_STUFF
    UNION ALL
    SELECT
        1 AS HAI_NUMBER_COLUMN_STUFF,
        2.2 AS HAI_DECIMAL_COLUMN_STUFF,
        3 AS HAI_NUMERIC_COLUMN_STUFF,
        'asdf' AS HAI_STRING_COLUMN_STUFF
)

SELECT *
FROM FAKE_DATA
