version: 2

sources:
  - name: new_config_source
    config:
      y42_source:
        type: source-google-sheets
        connection: "bt_gsheet"
    tables:
      - name: y42_demo
        config:
          y42_table:
            import: y42_demo
            columns:
              - id
              - name
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
            group: null
            supported_sync_modes:
              - full_refresh
            default_cursor_field: null
            source_defined_cursor: null
            source_defined_primary_key: null
