version: 2
sources:
  - name: airbyte_bigquery_old
    config:
      y42_source:
        type: source-bigquery
        connection: bigquery_bathien-us-playground
      asset_status: verified
      experts:
        users:
          - alexander.ciesielski@y42.com
        teams: []
    tables:
      - name: repeated_record
        config:
          y42_table:
            import: repeated_record
            columns:
              - repeated_record
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                repeated_record:
                  type: object
            group: playground
            _datos_write_settings:
              max_flatten_depth: 0
              decimals: false
            supported_sync_modes:
              - full_refresh
              - incremental
            default_cursor_field: []
            source_defined_cursor: null
            source_defined_primary_key: []
          asset_status: deprecated
        columns:
          - name: amazing
            description: amazing description
      - name: from_eu_playground
        config:
          y42_table:
            import: from_eu_playground
            columns:
              - id
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                id:
                  type: string
            group: playground
            supported_sync_modes:
              - full_refresh
              - incremental
            default_cursor_field: []
            source_defined_cursor: null
            source_defined_primary_key: []
      - name: cereal
        config:
          y42_table:
            import: cereal
            columns:
              - Cereal_Name
              - Protein__g_
              - Display_Shelf
              - Calories
              - Type
              - Cups_per_Serving
              - Sodium
              - Vitamins_and_Minerals
              - Manufacturer
              - Fat
              - Carbs
              - Serving_Size_Weight
              - Dietary_Fiber
              - Potassium
              - Sugars
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                Cereal_Name:
                  type: string
                Protein__g_:
                  type: number
                  airbyte_type: integer
                Display_Shelf:
                  type: number
                  airbyte_type: integer
                Calories:
                  type: number
                  airbyte_type: integer
                Type:
                  type: string
                Cups_per_Serving:
                  type: number
                Sodium:
                  type: number
                  airbyte_type: integer
                Vitamins_and_Minerals:
                  type: number
                  airbyte_type: integer
                Manufacturer:
                  type: string
                Fat:
                  type: number
                  airbyte_type: integer
                Carbs:
                  type: number
                Serving_Size_Weight:
                  type: number
                Dietary_Fiber:
                  type: number
                Potassium:
                  type: number
                  airbyte_type: integer
                Sugars:
                  type: number
                  airbyte_type: integer
            group: playground
            supported_sync_modes:
              - full_refresh
              - incremental
            default_cursor_field:
              - Cereal_Name
            source_defined_cursor: null
            source_defined_primary_key: []
        description: test2
        columns:
          - name: Sodium
            data_type: FLOAT
            tests:
              - not_null
          - name: Display_Shelf
            data_type: FLOAT
            tests:
              - not_null
          - name: Potassium
            data_type: FLOAT
          - name: Cereal_Name
            data_type: TEXT
          - name: Serving_Size_Weight
            data_type: FLOAT
          - name: Fat
            data_type: FLOAT
          - name: Dietary_Fiber
            data_type: FLOAT
          - name: Manufacturer
            data_type: TEXT
          - name: Type
            data_type: TEXT
          - name: Calories
            data_type: FLOAT
          - name: Sugars
            data_type: FLOAT
          - name: Carbs
            data_type: FLOAT
          - name: Cups_per_Serving
            data_type: FLOAT
          - name: Vitamins_and_Minerals
            data_type: FLOAT
          - name: Protein_g_
            data_type: FLOAT
        tags: []
        meta:
          experts:
            users: []
            teams: []
          asset_status: no status
          tier: no tier
      - name: playground_all_data_types
        config:
          y42_table:
            import: all_data_types
            columns:
              - float_field
              - json_field
              - record_field
              - integer_field
              - timestamp_field
              - datetime_field
              - string_field
              - date_field
              - array_field
              - time_field
              - geography_field
              - bytes_field
              - numeric_field
              - bignumeric_field
              - boolean_field
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                float_field:
                  type: number
                json_field:
                  type: string
                record_field:
                  type: object
                integer_field:
                  type: number
                  airbyte_type: integer
                timestamp_field:
                  type: string
                datetime_field:
                  type: string
                string_field:
                  type: string
                date_field:
                  type: string
                array_field:
                  type: string
                time_field:
                  type: string
                geography_field:
                  type: string
                bytes_field:
                  type: string
                numeric_field:
                  type: number
                bignumeric_field:
                  type: number
                boolean_field:
                  type: boolean
            group: playground
            supported_sync_modes:
              - full_refresh
              - incremental
            default_cursor_field: []
            source_defined_cursor: null
            source_defined_primary_key: []
    description: "some test ss"
  - name: airbyte_file_import
    config:
      y42_source:
        type: source-file
        connection: cereal_file
    meta:
      asset_status: verified
    tables:
      - name: cereal_bla
        config:
          y42_table:
            type: source-file
            import: cereal
            connection: cereal_file
            columns:
              - Cereal Name
              - Manufacturer
              - Type
              - Calories
              - Protein (g)
              - Fat
              - Sodium
              - Dietary Fiber
              - Carbs
              - Sugars
              - Display Shelf
              - Potassium
              - Vitamins and Minerals
              - Serving Size Weight
              - Cups per Serving
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                Cereal Name:
                  type:
                    - string
                    - "null"
                Manufacturer:
                  type:
                    - string
                    - "null"
                Type:
                  type:
                    - string
                    - "null"
                Calories:
                  type:
                    - number
                    - "null"
                Protein (g):
                  type:
                    - number
                    - "null"
                Fat:
                  type:
                    - number
                    - "null"
                Sodium:
                  type:
                    - number
                    - "null"
                Dietary Fiber:
                  type:
                    - number
                    - "null"
                Carbs:
                  type:
                    - number
                    - "null"
                Sugars:
                  type:
                    - number
                    - "null"
                Display Shelf:
                  type:
                    - number
                    - "null"
                Potassium:
                  type:
                    - number
                    - "null"
                Vitamins and Minerals:
                  type:
                    - number
                    - "null"
                Serving Size Weight:
                  type:
                    - number
                    - "null"
                Cups per Serving:
                  type:
                    - number
                    - "null"
            group: null
            supported_sync_modes:
              - full_refresh
            default_cursor_field: null
            source_defined_cursor: null
            source_defined_primary_key: null
  - name: intercom
    config:
      y42_source:
        type: intercom
        connection: intercom
      asset_status: verified
    tables:
      - name: admins
        config:
          y42_table:
            import: admins
            columns:
              - type
              - email
              - id
              - name
              - away_mode_enabled
              - away_mode_reassign
              - has_inbox_seat
              - team_ids
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                type:
                  type: string
                email:
                  type: string
                id:
                  type: string
                name:
                  type: string
                away_mode_enabled:
                  type: boolean
                away_mode_reassign:
                  type: boolean
                has_inbox_seat:
                  type: boolean
                team_ids:
                  type: array
        columns:
          - name: email
            data_type: STRING
          - name: away_mode_enabled
            data_type: BOOLEAN
          - name: id
            data_type: STRING
            tests:
              - unique
          - name: team_ids
            data_type: STRING
          - name: away_mode_reassign
            data_type: BOOLEAN
          - name: has_inbox_seat
            data_type: BOOLEAN
          - name: type
            data_type: STRING
          - name: name
            data_type: STRING
  - name: nat
    tables:
      - name: PUBLIC_TEST_TABLE
        identifier: TEST_TABLE
        description: ""
        tags: []
        meta:
          experts:
            users: []
            teams: []
          asset_status: no status
          tier: no tier
    database: ADRIAN_TEST_DB
    schema: PUBLIC
