sources:
  - name: testviewmanager
    meta:
      config:
        type: source-bigquery
        connection: btt_bigquery
    tables:
      - name: repeated_record
        meta:
          source_config:
            import: repeated_record
            columns:
              - repeated_record
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                repeated_record:
                  type: object
  - name: viewmanagertestbranch0001
    meta:
      config:
        type: source-bigquery
        connection: btt_bigquery
    tables:
      - name: 20230314_gads
        meta:
          source_config:
            import: 20230314_gads
            columns:
              - segments
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                segments:
                  type: object
