version: 2

sources:
  - name: testviewmanager
    meta:
      config:
        type: source-bigquery
        connection: btt_bigquery
    tables:
      - name: repeated_record
        meta:
          source_config:
            import: repeated_record
            columns:
              - repeated_record
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                repeated_record:
                  type: object
            group: playground
            supported_sync_modes:
              - full_refresh
              - incremental
            default_cursor_field: []
            source_defined_cursor: null
            source_defined_primary_key: []
  - name: viewmanagertestbranch0001
    meta:
      config:
        type: source-bigquery
        connection: btt_bigquery
    tables:
      - name: from_eu_playground
        meta:
          source_config:
            import: from_eu_playground
            columns:
              - id
            schema:
              $schema: http://json-schema.org/draft-07/schema#
              type: object
              properties:
                id:
                  type: string
            group: playground
            supported_sync_modes:
              - full_refresh
              - incremental
            default_cursor_field: []
            source_defined_cursor: null
            source_defined_primary_key: []
